<a href="https://colab.research.google.com/github/MonalSD/ML/blob/main/FeatureScaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from sklearn import preprocessing

In [4]:
x = np.array([[1.,-1.,2.],
              [2.,0.,0.],
              [0.,1.,-1.]])

In [7]:
x_scaled = preprocessing.scale(x)

In [8]:
x_scaled.mean(axis =0)

array([0., 0., 0.])

In [9]:
x_scaled.std(axis =0)

array([1., 1., 1.])

In [10]:
scaler = preprocessing.StandardScaler()
scaler.fit(x)

scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [11]:
X_test = [[1,1,0]]

In [12]:
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])